### ISSUE TITLE
Redo Layout

### ISSUE THREAD

**Issue by SirMoM** [teamvilbel/NQueensProblemWithProcessingAndProlog#11]
Redo Layout für das Brett und die Knöpfe sowohl mit als auch ohne User Input.
Vorallem auch für #9, #10
Denn ab einer bestimmten Größe werden Buttons über dem Brett angezeigt.

**Comment by SirMoM** [comment]
@jeanpauledoh  oder @aMJenger bitte testen

**Comment by jeanpauledoh** [comment]
Wenn man das Programm startet und wiederholt  auf  zwischen dem 'UserInput'-Screen und dem MainMenu hin und her geht, wandern der 'SOVE' und 'Resize'-Button immer weiter nach unten.

**Comment by jeanpauledoh** [comment]
Wenn das Enter-Board-Size-Fenster offen ist, lassen sich Queens drüber legen.

**Comment by jeanpauledoh** [comment]
![image](https://user-images.githubusercontent.com/33167296/71786675-3f6ced00-300e-11ea-91b1-a7f7a4caf279.png)

**Comment by SirMoM** [comment]
Beide Probleme sollten gefixed sein 👍
Aber bitte einfach nochmal testen.

**Comment by jeanpauledoh** [comment]
@SirMoM Beide Probleme sind gefixt, aber der 'Reset'-Button funktioniert nicht mehr. Das Board wird nicht mehr zurückgesetzt wenn man auf ihn klickt. Nur ein Resize des Boards setzt es zurück.

**Comment by SirMoM** [comment]
Ist gefixed mit: 232f3d41e229e89a227efec021d4b92c45663cf7

**Comment by SirMoM** [comment]
Wurde das getestet? Wenn ja bitte Issue schließen.

**Comment by aMJenger** [comment]
scheint alles zu funktionieren
