### ISSUE TITLE
Abbrechen einer Berechnung wenn diese zu lange dauert.

### ISSUE THREAD

**Issue by jeanpauledoh** [teamvilbel/NQueensProblemWithProcessingAndProlog#12]
Nur eine Idee am Rande: Ein Abbrechen-Button mit dem man eine aktuelle Berechnung abbrechen kann ohne das Programm schließen zu müssen. Evtl. wäre eine Timer wie lange eine Berechnung schon läuft auch cool.

**Comment by SirMoM** [comment]
Ja das Problem ist dann müsste die Berechnung in einen Thread gelegt werden. Und damit hab ich mich noch nicht beschäftigt. Denn ich hab kp ob sie API Thread-Safe ist usw.

**Comment by jeanpauledoh** [comment]
Alles klar, war nur ne Idee. Den Aufwand ist es nicht unbedingt wert.

**Comment by SirMoM** [comment]
Wenn jmd. Bock und Zeit kann man das bestimmt umsetzen ^^
