### ISSUE TITLE
NullPointer bei UserInput wenn direkt auf Prev oder Next geklickt wird

### ISSUE THREAD

**Issue by aMJenger** [teamvilbel/NQueensProblemWithProcessingAndProlog#13]
Null Pointer Exception fliegt, wenn man beim User Input direkt auf Next oder Prev klickt obwohl dort noch nichts ist.

**Comment by SirMoM** [comment]
Bitte testen sollte gefixed sein 👍

**Comment by jeanpauledoh** [comment]
Sieht gut aus, keine Exception fliegt.
