### ISSUE TITLE
Präsentation 

### ISSUE THREAD

**Issue by SirMoM** [teamvilbel/NQueensProblemWithProcessingAndProlog#5]
Bitte link kommentieren.

**Comment by jeanpauledoh** [comment]
welchen link?

**Comment by SirMoM** [comment]
Den der Google-Präsentation

**Comment by jeanpauledoh** [comment]
Alles klar

**Comment by aMJenger** [comment]
https://docs.google.com/presentation/d/1UYXhSzIbVzhI_RLq4vjIKnuQiMRNWqlZ2Tr2dp-IChA/edit?usp=sharing
