### ISSUE TITLE
Damen lassen sich nicht hinzufügen

### ISSUE THREAD

**Issue by SirMoM** [teamvilbel/NQueensProblemWithProcessingAndProlog#6]
Wenn man sich das Rätsel lösen lässt und dann Damen entfernt kann man die nicht wieder hinzufügen

**Comment by SirMoM** [comment]
@aMJenger 
Du hast das gefixed indem man einfach keine Damen mehr entfernen kann, wenn es eine Lösung gibt richtig ?

**Comment by jeanpauledoh** [comment]
zumindest verhält sich das Programm so
