### ISSUE TITLE
Nur User Input (aufs Brett) wenn das ausgewählt wurde.

### ISSUE THREAD

**Issue by SirMoM** [teamvilbel/NQueensProblemWithProcessingAndProlog#7]
Das Entfernen von Damen sollte nicht möglich sein, wenn man 4x4, 8x8 usw. auswählt

**Comment by SirMoM** [comment]
@jeanpauledoh teste mal ob das gefixt ist ^^

**Comment by jeanpauledoh** [comment]
**Ist nicht gefixt**
4x4:
- geht man direkt nach 'Start' auf '4x4' ist alles in Ordnung und man kann die Queens nicht entfernen. Es fehlt nur die Meldung das keine weitere Solution mehr da ist nach dem man auf Next geklickt hat.

- geht man erst auf 'User Input' dann 'Back', 'Start' und dann '4x4', dann taucht unter '4x4' der 'Solve'-Button auf und man kann nach dem man auf 'Solve' geklickt hat Queens entfernen und wieder hinzufügen. Klickt man danach auf 'Next' gibts ne ArrayIndexOutOfBoundsException und das Programm ist tot.
StackTrace:
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:422)
	at java.util.ArrayList.get(ArrayList.java:435)
	at thm.vilbel.com.processing.ProcessingApplication$10.doAction(ProcessingApplication.java:169)
	at thm.vilbel.com.processing.button.ProcessingButton.mousePressed(ProcessingButton.java:148)
	at thm.vilbel.com.processing.ProcessingApplication.mouseClicked(ProcessingApplication.java:485)
	at processing.core.PApplet.mouseClicked(PApplet.java:2817)
	at processing.core.PApplet.handleMouseEvent(PApplet.java:2697)
	at processing.core.PApplet.dequeueEvents(PApplet.java:2607)
	at processing.core.PApplet.handleDraw(PApplet.java:2448)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1557)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)
8x8:
- das gleiche: geht man direkt nach 'Start' auf '8x8' ist alles gut. Geht man über 'UserInput' dann ist unter '8x8' der 'Solve'-Button zu sehen. Klickt man drauf ist kommt die Meldung das nur eine Solution verfügbar ist und über 'Next' können keine weiteren Solutions mehr angezeigt werden und Queens können NICHT entfernt werden.  Klickt man danach auf 'Next' gibts ne ArrayIndexOutOfBoundsException und das Programm ist tot. 

10x10:
- geht man über 'UserInput' dann taucht der 'Solve'-Button im Spielfeld auf. Klickt man auf den Button dann kommt die Meldung das für diese Konfiguration keine Solutions mehr angezeigt werden können. Hier können danach auch Queens entfernt und hinzufügt werden. Klickt man danach auf 'Next' gibts ne ArrayIndexOutOfBoundsException und das Programm ist tot.
StackTrace: Gleiche Stelle wie bei '4x4'

**Comment by SirMoM** [comment]
Also ist das Problem, wenn man vom User Input in Optionen geht die keinen User Input haben richtig?

**Comment by SirMoM** [comment]
Ich glaube das hab ich auch mit Commit https://github.com/teamvilbel/NQueensProblemWithProcessingAndProlog/commit/fbe0fccb793720291f615b451260e342f0b1037e gefixed aber denke das sollte man nochmal testen.

**Comment by jeanpauledoh** [comment]
Ok, ja genau wenn man vom User Input in Optionen geht die keinen User Input haben...

**Comment by jeanpauledoh** [comment]
alles gut und läuft stabil
