### ISSUE TITLE
Anzeigen wie viele Solutions es gibt

### ISSUE THREAD

**Issue by jeanpauledoh** [teamvilbel/NQueensProblemWithProcessingAndProlog#9]
Momentan sieht man nur im Terminal wie viele Solutions es für die jeweilige Feldgröße gibt. Villt. könnte man ja ne Anzeige einbauen wie oft man 'Next' drücken kann und evtl auch anzeigen das keine neuen Solutions mehr verfügbar sind wenn man die letzte erreicht hat.

**Comment by SirMoM** [comment]
gibt es aber bis jetzt nur im user input teil

**Comment by SirMoM** [comment]
oder möchtest du das mit einem dauerhaften label machen?

**Comment by jeanpauledoh** [comment]
ich hab an ein dauerhaftes gedacht, aber wegen mir muss das nicht rein...das programm muss ja nicht schön aussehen solang es funktioniert

**Comment by SirMoM** [comment]
@jeanpauledoh bitte testen!!!

**Comment by jeanpauledoh** [comment]
Morgen dann

**Comment by jeanpauledoh** [comment]
sieht gut aus, danke
